/*
 * This file is generated by jOOQ.
 */
package com.hologramsciences.jooq.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import com.hologramsciences.jooq.Keys;
import com.hologramsciences.jooq.Public;
import com.hologramsciences.jooq.tables.records.RestaurantsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Restaurants extends TableImpl<RestaurantsRecord> {

    private static final long serialVersionUID = -866673604;

    /**
     * The reference instance of <code>PUBLIC.RESTAURANTS</code>
     */
    public static final Restaurants RESTAURANTS = new Restaurants();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RestaurantsRecord> getRecordType() {
        return RestaurantsRecord.class;
    }

    /**
     * The column <code>PUBLIC.RESTAURANTS.ID</code>.
     */
    public final TableField<RestaurantsRecord, Long> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.RESTAURANTS.NAME</code>.
     */
    public final TableField<RestaurantsRecord, String> NAME = createField(DSL.name("NAME"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>PUBLIC.RESTAURANTS</code> table reference
     */
    public Restaurants() {
        this(DSL.name("RESTAURANTS"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.RESTAURANTS</code> table reference
     */
    public Restaurants(String alias) {
        this(DSL.name(alias), RESTAURANTS);
    }

    /**
     * Create an aliased <code>PUBLIC.RESTAURANTS</code> table reference
     */
    public Restaurants(Name alias) {
        this(alias, RESTAURANTS);
    }

    private Restaurants(Name alias, Table<RestaurantsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Restaurants(Name alias, Table<RestaurantsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Restaurants(Table<O> child, ForeignKey<O, RestaurantsRecord> key) {
        super(child, key, RESTAURANTS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<RestaurantsRecord, Long> getIdentity() {
        return Keys.IDENTITY_RESTAURANTS;
    }

    @Override
    public UniqueKey<RestaurantsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_B;
    }

    @Override
    public List<UniqueKey<RestaurantsRecord>> getKeys() {
        return Arrays.<UniqueKey<RestaurantsRecord>>asList(Keys.CONSTRAINT_B);
    }

    @Override
    public Restaurants as(String alias) {
        return new Restaurants(DSL.name(alias), this);
    }

    @Override
    public Restaurants as(Name alias) {
        return new Restaurants(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Restaurants rename(String name) {
        return new Restaurants(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Restaurants rename(Name name) {
        return new Restaurants(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
