INSERT INTO restaurants (name) values ('Kushi Tsuru');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1260 from restaurants where name = 'Kushi Tsuru';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1260 from restaurants where name = 'Kushi Tsuru';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1260 from restaurants where name = 'Kushi Tsuru';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1260 from restaurants where name = 'Kushi Tsuru';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1260 from restaurants where name = 'Kushi Tsuru';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1260 from restaurants where name = 'Kushi Tsuru';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 690, 1260 from restaurants where name = 'Kushi Tsuru';
INSERT INTO restaurants (name) values ('Osakaya Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1290 from restaurants where name = 'Osakaya Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1260 from restaurants where name = 'Osakaya Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1260 from restaurants where name = 'Osakaya Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1260 from restaurants where name = 'Osakaya Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1260 from restaurants where name = 'Osakaya Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 690, 1260 from restaurants where name = 'Osakaya Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1290 from restaurants where name = 'Osakaya Restaurant';
INSERT INTO restaurants (name) values ('The Stinking Rose');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1380 from restaurants where name = 'The Stinking Rose';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1320 from restaurants where name = 'The Stinking Rose';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1320 from restaurants where name = 'The Stinking Rose';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1320 from restaurants where name = 'The Stinking Rose';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1320 from restaurants where name = 'The Stinking Rose';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 690, 1320 from restaurants where name = 'The Stinking Rose';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1380 from restaurants where name = 'The Stinking Rose';
INSERT INTO restaurants (name) values ('McCormick & Kuleto''s');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1380 from restaurants where name = 'McCormick & Kuleto''s';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1320 from restaurants where name = 'McCormick & Kuleto''s';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1320 from restaurants where name = 'McCormick & Kuleto''s';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1320 from restaurants where name = 'McCormick & Kuleto''s';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1320 from restaurants where name = 'McCormick & Kuleto''s';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 690, 1320 from restaurants where name = 'McCormick & Kuleto''s';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1380 from restaurants where name = 'McCormick & Kuleto''s';
INSERT INTO restaurants (name) values ('Mifune Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1320 from restaurants where name = 'Mifune Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1320 from restaurants where name = 'Mifune Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1320 from restaurants where name = 'Mifune Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1320 from restaurants where name = 'Mifune Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1320 from restaurants where name = 'Mifune Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 1320 from restaurants where name = 'Mifune Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1320 from restaurants where name = 'Mifune Restaurant';
INSERT INTO restaurants (name) values ('The Cheesecake Factory');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 30 from restaurants where name = 'The Cheesecake Factory';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1380 from restaurants where name = 'The Cheesecake Factory';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1380 from restaurants where name = 'The Cheesecake Factory';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1380 from restaurants where name = 'The Cheesecake Factory';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1380 from restaurants where name = 'The Cheesecake Factory';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 30 from restaurants where name = 'The Cheesecake Factory';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 600, 1380 from restaurants where name = 'The Cheesecake Factory';
INSERT INTO restaurants (name) values ('New Delhi Indian Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1320 from restaurants where name = 'New Delhi Indian Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1320 from restaurants where name = 'New Delhi Indian Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1320 from restaurants where name = 'New Delhi Indian Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1320 from restaurants where name = 'New Delhi Indian Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1320 from restaurants where name = 'New Delhi Indian Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1320 from restaurants where name = 'New Delhi Indian Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 1050, 1320 from restaurants where name = 'New Delhi Indian Restaurant';
INSERT INTO restaurants (name) values ('Iroha Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1320 from restaurants where name = 'Iroha Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1290 from restaurants where name = 'Iroha Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1290 from restaurants where name = 'Iroha Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1290 from restaurants where name = 'Iroha Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1290 from restaurants where name = 'Iroha Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 690, 1290 from restaurants where name = 'Iroha Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1320 from restaurants where name = 'Iroha Restaurant';
INSERT INTO restaurants (name) values ('Rose Pistola');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1380 from restaurants where name = 'Rose Pistola';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1320 from restaurants where name = 'Rose Pistola';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1320 from restaurants where name = 'Rose Pistola';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1320 from restaurants where name = 'Rose Pistola';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1320 from restaurants where name = 'Rose Pistola';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1380 from restaurants where name = 'Rose Pistola';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 690, 1380 from restaurants where name = 'Rose Pistola';
INSERT INTO restaurants (name) values ('Alioto''s Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1380 from restaurants where name = 'Alioto''s Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1380 from restaurants where name = 'Alioto''s Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1380 from restaurants where name = 'Alioto''s Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1380 from restaurants where name = 'Alioto''s Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1380 from restaurants where name = 'Alioto''s Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 1380 from restaurants where name = 'Alioto''s Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1380 from restaurants where name = 'Alioto''s Restaurant';
INSERT INTO restaurants (name) values ('Canton Seafood & Dim Sum Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 630, 1290 from restaurants where name = 'Canton Seafood & Dim Sum Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 630, 1290 from restaurants where name = 'Canton Seafood & Dim Sum Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 630, 1290 from restaurants where name = 'Canton Seafood & Dim Sum Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 630, 1290 from restaurants where name = 'Canton Seafood & Dim Sum Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 630, 1290 from restaurants where name = 'Canton Seafood & Dim Sum Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 600, 1290 from restaurants where name = 'Canton Seafood & Dim Sum Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 600, 1290 from restaurants where name = 'Canton Seafood & Dim Sum Restaurant';
INSERT INTO restaurants (name) values ('All Season Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 600, 1290 from restaurants where name = 'All Season Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 600, 1290 from restaurants where name = 'All Season Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 600, 1290 from restaurants where name = 'All Season Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 600, 1290 from restaurants where name = 'All Season Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 600, 1290 from restaurants where name = 'All Season Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 570, 1290 from restaurants where name = 'All Season Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 570, 1290 from restaurants where name = 'All Season Restaurant';
INSERT INTO restaurants (name) values ('Bombay Indian Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1350 from restaurants where name = 'Bombay Indian Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1350 from restaurants where name = 'Bombay Indian Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1350 from restaurants where name = 'Bombay Indian Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1350 from restaurants where name = 'Bombay Indian Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1350 from restaurants where name = 'Bombay Indian Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1350 from restaurants where name = 'Bombay Indian Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 690, 1350 from restaurants where name = 'Bombay Indian Restaurant';
INSERT INTO restaurants (name) values ('Sam''s Grill & Seafood Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1260 from restaurants where name = 'Sam''s Grill & Seafood Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1260 from restaurants where name = 'Sam''s Grill & Seafood Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1260 from restaurants where name = 'Sam''s Grill & Seafood Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1260 from restaurants where name = 'Sam''s Grill & Seafood Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1260 from restaurants where name = 'Sam''s Grill & Seafood Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 1020, 1260 from restaurants where name = 'Sam''s Grill & Seafood Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 1020, 1260 from restaurants where name = 'Sam''s Grill & Seafood Restaurant';
INSERT INTO restaurants (name) values ('2G Japanese Brasserie');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1380 from restaurants where name = '2G Japanese Brasserie';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1320 from restaurants where name = '2G Japanese Brasserie';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1320 from restaurants where name = '2G Japanese Brasserie';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1320 from restaurants where name = '2G Japanese Brasserie';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1320 from restaurants where name = '2G Japanese Brasserie';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1320 from restaurants where name = '2G Japanese Brasserie';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 1380 from restaurants where name = '2G Japanese Brasserie';
INSERT INTO restaurants (name) values ('Restaurant Lulu');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1320 from restaurants where name = 'Restaurant Lulu';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1260 from restaurants where name = 'Restaurant Lulu';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1260 from restaurants where name = 'Restaurant Lulu';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1260 from restaurants where name = 'Restaurant Lulu';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1260 from restaurants where name = 'Restaurant Lulu';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 690, 1260 from restaurants where name = 'Restaurant Lulu';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1320 from restaurants where name = 'Restaurant Lulu';
INSERT INTO restaurants (name) values ('Sudachi');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 1020, 90 from restaurants where name = 'Sudachi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 1020, 30 from restaurants where name = 'Sudachi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 1020, 30 from restaurants where name = 'Sudachi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 1020, 30 from restaurants where name = 'Sudachi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 1020, 90 from restaurants where name = 'Sudachi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 900, 90 from restaurants where name = 'Sudachi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 900, 1410 from restaurants where name = 'Sudachi';
INSERT INTO restaurants (name) values ('Hanuri');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 0 from restaurants where name = 'Hanuri';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 0 from restaurants where name = 'Hanuri';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 0 from restaurants where name = 'Hanuri';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 0 from restaurants where name = 'Hanuri';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 0 from restaurants where name = 'Hanuri';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 0 from restaurants where name = 'Hanuri';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 0 from restaurants where name = 'Hanuri';
INSERT INTO restaurants (name) values ('Herbivore');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 540, 1380 from restaurants where name = 'Herbivore';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 540, 1320 from restaurants where name = 'Herbivore';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 540, 1320 from restaurants where name = 'Herbivore';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 540, 1320 from restaurants where name = 'Herbivore';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 540, 1320 from restaurants where name = 'Herbivore';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 540, 1320 from restaurants where name = 'Herbivore';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 540, 1380 from restaurants where name = 'Herbivore';
INSERT INTO restaurants (name) values ('Penang Garden');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 600, 1350 from restaurants where name = 'Penang Garden';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1320 from restaurants where name = 'Penang Garden';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1320 from restaurants where name = 'Penang Garden';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1320 from restaurants where name = 'Penang Garden';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1320 from restaurants where name = 'Penang Garden';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 600, 1350 from restaurants where name = 'Penang Garden';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1380 from restaurants where name = 'Penang Garden';
INSERT INTO restaurants (name) values ('John''s Grill');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1320 from restaurants where name = 'John''s Grill';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1320 from restaurants where name = 'John''s Grill';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1320 from restaurants where name = 'John''s Grill';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1320 from restaurants where name = 'John''s Grill';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1320 from restaurants where name = 'John''s Grill';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 1320 from restaurants where name = 'John''s Grill';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 720, 1320 from restaurants where name = 'John''s Grill';
INSERT INTO restaurants (name) values ('Quan Bac');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1320 from restaurants where name = 'Quan Bac';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1320 from restaurants where name = 'Quan Bac';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1320 from restaurants where name = 'Quan Bac';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1320 from restaurants where name = 'Quan Bac';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1320 from restaurants where name = 'Quan Bac';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 1320 from restaurants where name = 'Quan Bac';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1320 from restaurants where name = 'Quan Bac';
INSERT INTO restaurants (name) values ('Bamboo Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 0 from restaurants where name = 'Bamboo Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 0 from restaurants where name = 'Bamboo Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 0 from restaurants where name = 'Bamboo Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 0 from restaurants where name = 'Bamboo Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 0 from restaurants where name = 'Bamboo Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 0 from restaurants where name = 'Bamboo Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 720, 0 from restaurants where name = 'Bamboo Restaurant';
INSERT INTO restaurants (name) values ('Burger Bar');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 0 from restaurants where name = 'Burger Bar';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1320 from restaurants where name = 'Burger Bar';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1320 from restaurants where name = 'Burger Bar';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1320 from restaurants where name = 'Burger Bar';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1320 from restaurants where name = 'Burger Bar';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1320 from restaurants where name = 'Burger Bar';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 0 from restaurants where name = 'Burger Bar';
INSERT INTO restaurants (name) values ('Blu Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1320 from restaurants where name = 'Blu Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1320 from restaurants where name = 'Blu Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1320 from restaurants where name = 'Blu Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1320 from restaurants where name = 'Blu Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1320 from restaurants where name = 'Blu Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 420, 900 from restaurants where name = 'Blu Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 420, 900 from restaurants where name = 'Blu Restaurant';
INSERT INTO restaurants (name) values ('Naan ''N'' Curry');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 960 from restaurants where name = 'Naan ''N'' Curry';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 960 from restaurants where name = 'Naan ''N'' Curry';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 960 from restaurants where name = 'Naan ''N'' Curry';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 960 from restaurants where name = 'Naan ''N'' Curry';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 960 from restaurants where name = 'Naan ''N'' Curry';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 960 from restaurants where name = 'Naan ''N'' Curry';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 960 from restaurants where name = 'Naan ''N'' Curry';
INSERT INTO restaurants (name) values ('Shanghai China Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1290 from restaurants where name = 'Shanghai China Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1290 from restaurants where name = 'Shanghai China Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1290 from restaurants where name = 'Shanghai China Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1290 from restaurants where name = 'Shanghai China Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1290 from restaurants where name = 'Shanghai China Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 1290 from restaurants where name = 'Shanghai China Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1290 from restaurants where name = 'Shanghai China Restaurant';
INSERT INTO restaurants (name) values ('Tres');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1380 from restaurants where name = 'Tres';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1320 from restaurants where name = 'Tres';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1320 from restaurants where name = 'Tres';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1320 from restaurants where name = 'Tres';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1320 from restaurants where name = 'Tres';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 690, 1320 from restaurants where name = 'Tres';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1380 from restaurants where name = 'Tres';
INSERT INTO restaurants (name) values ('Isobune Sushi');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1290 from restaurants where name = 'Isobune Sushi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1290 from restaurants where name = 'Isobune Sushi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1290 from restaurants where name = 'Isobune Sushi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1290 from restaurants where name = 'Isobune Sushi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1290 from restaurants where name = 'Isobune Sushi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1290 from restaurants where name = 'Isobune Sushi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 690, 1290 from restaurants where name = 'Isobune Sushi';
INSERT INTO restaurants (name) values ('Viva Pizza Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 0 from restaurants where name = 'Viva Pizza Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 0 from restaurants where name = 'Viva Pizza Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 0 from restaurants where name = 'Viva Pizza Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 0 from restaurants where name = 'Viva Pizza Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 0 from restaurants where name = 'Viva Pizza Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 0 from restaurants where name = 'Viva Pizza Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 0 from restaurants where name = 'Viva Pizza Restaurant';
INSERT INTO restaurants (name) values ('Far East Cafe');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1320 from restaurants where name = 'Far East Cafe';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1320 from restaurants where name = 'Far East Cafe';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1320 from restaurants where name = 'Far East Cafe';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1320 from restaurants where name = 'Far East Cafe';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1320 from restaurants where name = 'Far East Cafe';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1320 from restaurants where name = 'Far East Cafe';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 690, 1320 from restaurants where name = 'Far East Cafe';
INSERT INTO restaurants (name) values ('Parallel 37');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1320 from restaurants where name = 'Parallel 37';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1320 from restaurants where name = 'Parallel 37';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1320 from restaurants where name = 'Parallel 37';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1320 from restaurants where name = 'Parallel 37';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1320 from restaurants where name = 'Parallel 37';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1320 from restaurants where name = 'Parallel 37';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 690, 1320 from restaurants where name = 'Parallel 37';
INSERT INTO restaurants (name) values ('Bai Thong Thai Cuisine');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1380 from restaurants where name = 'Bai Thong Thai Cuisine';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1380 from restaurants where name = 'Bai Thong Thai Cuisine';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1380 from restaurants where name = 'Bai Thong Thai Cuisine';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1380 from restaurants where name = 'Bai Thong Thai Cuisine';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1380 from restaurants where name = 'Bai Thong Thai Cuisine';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 1380 from restaurants where name = 'Bai Thong Thai Cuisine';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1320 from restaurants where name = 'Bai Thong Thai Cuisine';
INSERT INTO restaurants (name) values ('Alhamra');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1380 from restaurants where name = 'Alhamra';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1380 from restaurants where name = 'Alhamra';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1380 from restaurants where name = 'Alhamra';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1380 from restaurants where name = 'Alhamra';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1380 from restaurants where name = 'Alhamra';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1380 from restaurants where name = 'Alhamra';
INSERT INTO restaurants (name) values ('A-1 Cafe Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1320 from restaurants where name = 'A-1 Cafe Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1320 from restaurants where name = 'A-1 Cafe Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1320 from restaurants where name = 'A-1 Cafe Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1320 from restaurants where name = 'A-1 Cafe Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 1320 from restaurants where name = 'A-1 Cafe Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1320 from restaurants where name = 'A-1 Cafe Restaurant';
INSERT INTO restaurants (name) values ('Nick''s Lighthouse');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1350 from restaurants where name = 'Nick''s Lighthouse';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1350 from restaurants where name = 'Nick''s Lighthouse';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1350 from restaurants where name = 'Nick''s Lighthouse';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1350 from restaurants where name = 'Nick''s Lighthouse';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1350 from restaurants where name = 'Nick''s Lighthouse';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 1350 from restaurants where name = 'Nick''s Lighthouse';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1350 from restaurants where name = 'Nick''s Lighthouse';
INSERT INTO restaurants (name) values ('Paragon Restaurant & Bar');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1320 from restaurants where name = 'Paragon Restaurant & Bar';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1320 from restaurants where name = 'Paragon Restaurant & Bar';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1320 from restaurants where name = 'Paragon Restaurant & Bar';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1320 from restaurants where name = 'Paragon Restaurant & Bar';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1320 from restaurants where name = 'Paragon Restaurant & Bar';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 1050, 1320 from restaurants where name = 'Paragon Restaurant & Bar';
INSERT INTO restaurants (name) values ('Chili Lemon Garlic');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1320 from restaurants where name = 'Chili Lemon Garlic';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1320 from restaurants where name = 'Chili Lemon Garlic';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1320 from restaurants where name = 'Chili Lemon Garlic';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1320 from restaurants where name = 'Chili Lemon Garlic';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1320 from restaurants where name = 'Chili Lemon Garlic';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 1020, 1320 from restaurants where name = 'Chili Lemon Garlic';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 1020, 1320 from restaurants where name = 'Chili Lemon Garlic';
INSERT INTO restaurants (name) values ('Bow Hon Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1350 from restaurants where name = 'Bow Hon Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1350 from restaurants where name = 'Bow Hon Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1350 from restaurants where name = 'Bow Hon Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1350 from restaurants where name = 'Bow Hon Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1350 from restaurants where name = 'Bow Hon Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 1350 from restaurants where name = 'Bow Hon Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1350 from restaurants where name = 'Bow Hon Restaurant';
INSERT INTO restaurants (name) values ('San Dong House');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1380 from restaurants where name = 'San Dong House';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1380 from restaurants where name = 'San Dong House';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1380 from restaurants where name = 'San Dong House';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1380 from restaurants where name = 'San Dong House';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1380 from restaurants where name = 'San Dong House';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 1380 from restaurants where name = 'San Dong House';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1380 from restaurants where name = 'San Dong House';
INSERT INTO restaurants (name) values ('Thai Stick Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 60 from restaurants where name = 'Thai Stick Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 60 from restaurants where name = 'Thai Stick Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 60 from restaurants where name = 'Thai Stick Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 60 from restaurants where name = 'Thai Stick Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 60 from restaurants where name = 'Thai Stick Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 60 from restaurants where name = 'Thai Stick Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 60 from restaurants where name = 'Thai Stick Restaurant';
INSERT INTO restaurants (name) values ('Cesario''s');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1350 from restaurants where name = 'Cesario''s';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1320 from restaurants where name = 'Cesario''s';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1320 from restaurants where name = 'Cesario''s';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1320 from restaurants where name = 'Cesario''s';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1320 from restaurants where name = 'Cesario''s';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 690, 1320 from restaurants where name = 'Cesario''s';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1350 from restaurants where name = 'Cesario''s';
INSERT INTO restaurants (name) values ('Colombini Italian Cafe Bistro');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 720, 1320 from restaurants where name = 'Colombini Italian Cafe Bistro';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 720, 1320 from restaurants where name = 'Colombini Italian Cafe Bistro';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 720, 1320 from restaurants where name = 'Colombini Italian Cafe Bistro';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 720, 1320 from restaurants where name = 'Colombini Italian Cafe Bistro';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 720, 1320 from restaurants where name = 'Colombini Italian Cafe Bistro';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 1020, 1320 from restaurants where name = 'Colombini Italian Cafe Bistro';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 1020, 1320 from restaurants where name = 'Colombini Italian Cafe Bistro';
INSERT INTO restaurants (name) values ('Sabella & La Torre');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 600, 30 from restaurants where name = 'Sabella & La Torre';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 600, 1350 from restaurants where name = 'Sabella & La Torre';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 600, 1350 from restaurants where name = 'Sabella & La Torre';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 600, 1350 from restaurants where name = 'Sabella & La Torre';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 600, 1350 from restaurants where name = 'Sabella & La Torre';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 600, 1350 from restaurants where name = 'Sabella & La Torre';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 600, 30 from restaurants where name = 'Sabella & La Torre';
INSERT INTO restaurants (name) values ('Soluna Cafe and Lounge');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 690, 1320 from restaurants where name = 'Soluna Cafe and Lounge';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 690, 1320 from restaurants where name = 'Soluna Cafe and Lounge';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 690, 1320 from restaurants where name = 'Soluna Cafe and Lounge';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 690, 1320 from restaurants where name = 'Soluna Cafe and Lounge';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 690, 1320 from restaurants where name = 'Soluna Cafe and Lounge';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 1020, 1320 from restaurants where name = 'Soluna Cafe and Lounge';
INSERT INTO restaurants (name) values ('Tong Palace');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 540, 1290 from restaurants where name = 'Tong Palace';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 540, 1290 from restaurants where name = 'Tong Palace';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 540, 1290 from restaurants where name = 'Tong Palace';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 540, 1290 from restaurants where name = 'Tong Palace';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 540, 1290 from restaurants where name = 'Tong Palace';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 540, 1380 from restaurants where name = 'Tong Palace';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 540, 1380 from restaurants where name = 'Tong Palace';
INSERT INTO restaurants (name) values ('India Garden Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 600, 1380 from restaurants where name = 'India Garden Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 600, 1380 from restaurants where name = 'India Garden Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 600, 1380 from restaurants where name = 'India Garden Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 600, 1380 from restaurants where name = 'India Garden Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 600, 1380 from restaurants where name = 'India Garden Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 600, 1380 from restaurants where name = 'India Garden Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 600, 1380 from restaurants where name = 'India Garden Restaurant';
INSERT INTO restaurants (name) values ('Sapporo-Ya Japanese Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1380 from restaurants where name = 'Sapporo-Ya Japanese Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1380 from restaurants where name = 'Sapporo-Ya Japanese Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1380 from restaurants where name = 'Sapporo-Ya Japanese Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1380 from restaurants where name = 'Sapporo-Ya Japanese Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1380 from restaurants where name = 'Sapporo-Ya Japanese Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 660, 1380 from restaurants where name = 'Sapporo-Ya Japanese Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 660, 1410 from restaurants where name = 'Sapporo-Ya Japanese Restaurant';
INSERT INTO restaurants (name) values ('Santorini''s Mediterranean Cuisine');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 480, 1350 from restaurants where name = 'Santorini''s Mediterranean Cuisine';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 480, 1350 from restaurants where name = 'Santorini''s Mediterranean Cuisine';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 480, 1350 from restaurants where name = 'Santorini''s Mediterranean Cuisine';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 480, 1350 from restaurants where name = 'Santorini''s Mediterranean Cuisine';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 480, 1350 from restaurants where name = 'Santorini''s Mediterranean Cuisine';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 480, 1350 from restaurants where name = 'Santorini''s Mediterranean Cuisine';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 480, 1350 from restaurants where name = 'Santorini''s Mediterranean Cuisine';
INSERT INTO restaurants (name) values ('Kyoto Sushi');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 660, 1380 from restaurants where name = 'Kyoto Sushi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 660, 1350 from restaurants where name = 'Kyoto Sushi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 660, 1350 from restaurants where name = 'Kyoto Sushi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 660, 1350 from restaurants where name = 'Kyoto Sushi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 660, 1350 from restaurants where name = 'Kyoto Sushi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 690, 1380 from restaurants where name = 'Kyoto Sushi';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 990, 1350 from restaurants where name = 'Kyoto Sushi';
INSERT INTO restaurants (name) values ('Marrakech Moroccan Restaurant');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 1050, 120 from restaurants where name = 'Marrakech Moroccan Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 1050, 120 from restaurants where name = 'Marrakech Moroccan Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 1050, 120 from restaurants where name = 'Marrakech Moroccan Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 1050, 120 from restaurants where name = 'Marrakech Moroccan Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 1050, 120 from restaurants where name = 'Marrakech Moroccan Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 1050, 120 from restaurants where name = 'Marrakech Moroccan Restaurant';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 1050, 120 from restaurants where name = 'Marrakech Moroccan Restaurant';
INSERT INTO restaurants (name) values ('Tim''s Nighttime Banana Stand');
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'FRIDAY', 1050, 360 from restaurants where name = 'Tim''s Nighttime Banana Stand';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'TUESDAY', 1050, 360 from restaurants where name = 'Tim''s Nighttime Banana Stand';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'MONDAY', 1050, 360 from restaurants where name = 'Tim''s Nighttime Banana Stand';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'WEDNESDAY', 1050, 360 from restaurants where name = 'Tim''s Nighttime Banana Stand';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'THURSDAY', 1050, 360 from restaurants where name = 'Tim''s Nighttime Banana Stand';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SATURDAY', 1050, 360 from restaurants where name = 'Tim''s Nighttime Banana Stand';
INSERT INTO open_hours (restaurant_id, day_of_week, start_time_minute_of_day, end_time_minute_of_day) select id, 'SUNDAY', 1050, 360 from restaurants where name = 'Tim''s Nighttime Banana Stand';
--
INSERT INTO menu_items (restaurant_id, name) select id, 'Salmon Hand Roll' from restaurants where name IN ('Sapporo-Ya Japanese Restaurant', 'Kyoto Sushi', 'Sudachi', 'Mifune Restaurant');
INSERT INTO menu_items (restaurant_id, name) select id, 'Tamago Nigiri'    from restaurants where name IN ('Sapporo-Ya Japanese Restaurant', 'Kyoto Sushi', 'Sudachi', 'Mifune Restaurant');
INSERT INTO menu_items (restaurant_id, name) select id , 'Strawberry Cheesecake' from restaurants where name = 'The Cheesecake Factory';
INSERT INTO menu_items (restaurant_id, name) select id , 'Peanut Butter Cheesecake' from restaurants where name = 'The Cheesecake Factory';
INSERT INTO menu_items (restaurant_id, name) select id , 'Bucatini Carbonara' from restaurants where name = 'The Cheesecake Factory';
INSERT INTO menu_items (restaurant_id, name) select id, 'Soup Dumplings' from restaurants where name = 'Shanghai China Restaurant';
INSERT INTO menu_items (restaurant_id, name) select id, 'Scallion Pancake' from restaurants where name = 'Shanghai China Restaurant';
INSERT INTO menu_items (restaurant_id, name) select id, 'Sichaun Spicy Fish' from restaurants where name = 'Shanghai China Restaurant';
