/*
 * This file is generated by jOOQ.
 */
package com.eatwithava.jooq;


import com.eatwithava.jooq.tables.MenuItems;
import com.eatwithava.jooq.tables.OpenHours;
import com.eatwithava.jooq.tables.Restaurants;
import com.eatwithava.jooq.tables.records.MenuItemsRecord;
import com.eatwithava.jooq.tables.records.OpenHoursRecord;
import com.eatwithava.jooq.tables.records.RestaurantsRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<MenuItemsRecord, Long> IDENTITY_MENU_ITEMS = Identities0.IDENTITY_MENU_ITEMS;
    public static final Identity<OpenHoursRecord, Long> IDENTITY_OPEN_HOURS = Identities0.IDENTITY_OPEN_HOURS;
    public static final Identity<RestaurantsRecord, Long> IDENTITY_RESTAURANTS = Identities0.IDENTITY_RESTAURANTS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MenuItemsRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
    public static final UniqueKey<OpenHoursRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
    public static final UniqueKey<RestaurantsRecord> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MenuItemsRecord, RestaurantsRecord> CONSTRAINT_4D = ForeignKeys0.CONSTRAINT_4D;
    public static final ForeignKey<OpenHoursRecord, RestaurantsRecord> CONSTRAINT_7C = ForeignKeys0.CONSTRAINT_7C;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<MenuItemsRecord, Long> IDENTITY_MENU_ITEMS = Internal.createIdentity(MenuItems.MENU_ITEMS, MenuItems.MENU_ITEMS.ID);
        public static Identity<OpenHoursRecord, Long> IDENTITY_OPEN_HOURS = Internal.createIdentity(OpenHours.OPEN_HOURS, OpenHours.OPEN_HOURS.ID);
        public static Identity<RestaurantsRecord, Long> IDENTITY_RESTAURANTS = Internal.createIdentity(Restaurants.RESTAURANTS, Restaurants.RESTAURANTS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<MenuItemsRecord> CONSTRAINT_4 = Internal.createUniqueKey(MenuItems.MENU_ITEMS, "CONSTRAINT_4", new TableField[] { MenuItems.MENU_ITEMS.ID }, true);
        public static final UniqueKey<OpenHoursRecord> CONSTRAINT_7 = Internal.createUniqueKey(OpenHours.OPEN_HOURS, "CONSTRAINT_7", new TableField[] { OpenHours.OPEN_HOURS.ID }, true);
        public static final UniqueKey<RestaurantsRecord> CONSTRAINT_B = Internal.createUniqueKey(Restaurants.RESTAURANTS, "CONSTRAINT_B", new TableField[] { Restaurants.RESTAURANTS.ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<MenuItemsRecord, RestaurantsRecord> CONSTRAINT_4D = Internal.createForeignKey(Keys.CONSTRAINT_B, MenuItems.MENU_ITEMS, "CONSTRAINT_4D", new TableField[] { MenuItems.MENU_ITEMS.RESTAURANT_ID }, true);
        public static final ForeignKey<OpenHoursRecord, RestaurantsRecord> CONSTRAINT_7C = Internal.createForeignKey(Keys.CONSTRAINT_B, OpenHours.OPEN_HOURS, "CONSTRAINT_7C", new TableField[] { OpenHours.OPEN_HOURS.RESTAURANT_ID }, true);
    }
}
