/*
 * This file is generated by jOOQ.
 */
package com.eatwithava.jooq;


import com.eatwithava.jooq.tables.MenuItems;
import com.eatwithava.jooq.tables.OpenHours;
import com.eatwithava.jooq.tables.Restaurants;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1150895750;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.MENU_ITEMS</code>.
     */
    public final MenuItems MENU_ITEMS = MenuItems.MENU_ITEMS;

    /**
     * The table <code>PUBLIC.OPEN_HOURS</code>.
     */
    public final OpenHours OPEN_HOURS = OpenHours.OPEN_HOURS;

    /**
     * The table <code>PUBLIC.RESTAURANTS</code>.
     */
    public final Restaurants RESTAURANTS = Restaurants.RESTAURANTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            MenuItems.MENU_ITEMS,
            OpenHours.OPEN_HOURS,
            Restaurants.RESTAURANTS);
    }
}
