/*
 * This file is generated by jOOQ.
 */
package com.eatwithava.jooq;


import com.eatwithava.jooq.tables.MenuItems;
import com.eatwithava.jooq.tables.OpenHours;
import com.eatwithava.jooq.tables.Restaurants;


/**
 * Convenience access to all tables in PUBLIC
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.MENU_ITEMS</code>.
     */
    public static final MenuItems MENU_ITEMS = MenuItems.MENU_ITEMS;

    /**
     * The table <code>PUBLIC.OPEN_HOURS</code>.
     */
    public static final OpenHours OPEN_HOURS = OpenHours.OPEN_HOURS;

    /**
     * The table <code>PUBLIC.RESTAURANTS</code>.
     */
    public static final Restaurants RESTAURANTS = Restaurants.RESTAURANTS;
}
