/*
 * This file is generated by jOOQ.
 */
package com.hologramsciences.jooq.tables.records;


import com.hologramsciences.jooq.tables.OpenHours;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpenHoursRecord extends UpdatableRecordImpl<OpenHoursRecord> implements Record5<Long, Long, String, Integer, Integer> {

    private static final long serialVersionUID = -1647962410;

    /**
     * Setter for <code>PUBLIC.OPEN_HOURS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.OPEN_HOURS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.OPEN_HOURS.RESTAURANT_ID</code>.
     */
    public void setRestaurantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.OPEN_HOURS.RESTAURANT_ID</code>.
     */
    public Long getRestaurantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.OPEN_HOURS.DAY_OF_WEEK</code>.
     */
    public void setDayOfWeek(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.OPEN_HOURS.DAY_OF_WEEK</code>.
     */
    public String getDayOfWeek() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.OPEN_HOURS.START_TIME_MINUTE_OF_DAY</code>.
     */
    public void setStartTimeMinuteOfDay(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.OPEN_HOURS.START_TIME_MINUTE_OF_DAY</code>.
     */
    public Integer getStartTimeMinuteOfDay() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.OPEN_HOURS.END_TIME_MINUTE_OF_DAY</code>.
     */
    public void setEndTimeMinuteOfDay(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.OPEN_HOURS.END_TIME_MINUTE_OF_DAY</code>.
     */
    public Integer getEndTimeMinuteOfDay() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OpenHours.OPEN_HOURS.ID;
    }

    @Override
    public Field<Long> field2() {
        return OpenHours.OPEN_HOURS.RESTAURANT_ID;
    }

    @Override
    public Field<String> field3() {
        return OpenHours.OPEN_HOURS.DAY_OF_WEEK;
    }

    @Override
    public Field<Integer> field4() {
        return OpenHours.OPEN_HOURS.START_TIME_MINUTE_OF_DAY;
    }

    @Override
    public Field<Integer> field5() {
        return OpenHours.OPEN_HOURS.END_TIME_MINUTE_OF_DAY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getRestaurantId();
    }

    @Override
    public String component3() {
        return getDayOfWeek();
    }

    @Override
    public Integer component4() {
        return getStartTimeMinuteOfDay();
    }

    @Override
    public Integer component5() {
        return getEndTimeMinuteOfDay();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getRestaurantId();
    }

    @Override
    public String value3() {
        return getDayOfWeek();
    }

    @Override
    public Integer value4() {
        return getStartTimeMinuteOfDay();
    }

    @Override
    public Integer value5() {
        return getEndTimeMinuteOfDay();
    }

    @Override
    public OpenHoursRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public OpenHoursRecord value2(Long value) {
        setRestaurantId(value);
        return this;
    }

    @Override
    public OpenHoursRecord value3(String value) {
        setDayOfWeek(value);
        return this;
    }

    @Override
    public OpenHoursRecord value4(Integer value) {
        setStartTimeMinuteOfDay(value);
        return this;
    }

    @Override
    public OpenHoursRecord value5(Integer value) {
        setEndTimeMinuteOfDay(value);
        return this;
    }

    @Override
    public OpenHoursRecord values(Long value1, Long value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OpenHoursRecord
     */
    public OpenHoursRecord() {
        super(OpenHours.OPEN_HOURS);
    }

    /**
     * Create a detached, initialised OpenHoursRecord
     */
    public OpenHoursRecord(Long id, Long restaurantId, String dayOfWeek, Integer startTimeMinuteOfDay, Integer endTimeMinuteOfDay) {
        super(OpenHours.OPEN_HOURS);

        set(0, id);
        set(1, restaurantId);
        set(2, dayOfWeek);
        set(3, startTimeMinuteOfDay);
        set(4, endTimeMinuteOfDay);
    }
}
